<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
	  <Description>Entity Framework layer for the administration of the IdentityServer4 and Asp.Net Core Identity with MySql support</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microting.EntityFrameworkCore.MySql" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NecroSharper.IdentityServer10.Admin.EntityFramework.Shared\NecroSharper.IdentityServer10.Admin.EntityFramework.Shared.csproj" />
  </ItemGroup>

</Project>
