<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
	  <Description>Entity Framework layer for the administration of the IdentityServer4</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OmarBaruzzo.IdentityServer10.EntityFramework" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.12" />
    <PackageReference Include="Skoruba.AuditLogging.EntityFramework" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NecroSharper.IdentityServer10.Admin.EntityFramework.Extensions\NecroSharper.IdentityServer10.Admin.EntityFramework.Extensions.csproj" />
  </ItemGroup>
</Project>
